# Generated by Django 4.0.4 on 2022-05-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
